### ISSUE TITLE
keep syncthing running after killing framework

### ISSUE THREAD

**Issue by lenisko** [gutenye/syncthing-kindle#1]
Hello there, is there any way to keep syncthing service running after killing framework by KOreader?

**Comment by gutenye** [comment]
What's KOreader and what does killing framework mean? I've never use it.

**Comment by lenisko** [comment]
Oh sorry.
KOreader - "An ebook reader application supports PDF, DJVU, EPUB, FB2 and much more, running on Kindle" - https://github.com/koreader/koreader

It's executing https://github.com/koreader/koreader/blob/master/platform/kindle/koreader.sh#L155-L170 this code, then syncthing which I started by KULA is killed too. Would be great to keep this process running in background.

**Comment by gutenye** [comment]
I have no idea how to fix it.
