### ISSUE TITLE
Can't visit GUI

### ISSUE THREAD

**Issue by zerone01y** [gutenye/syncthing-kindle#5]
First I'd thank you to maintain this repo, and the readme is very helpful. When I follow the guideline to set up my kindle (it's a kpw3 btw), I was just stuck in the middle and could not visit the syncthing GUI via my browser. 

I've already figured it out by myself, and want to share my experience here. Hope it helps anyone who has the same issue. 

What I did is are
1. ssh my kindle first (require USBNetwork)
2. Manually run the commands to open the firewall for port 8384, i.e., `iptables -A INPUT -i wlan0 -p tcp --dport 8384 -j ACCEPT`,
3. Edit the config file:  `nano /mnt/us/extensions//syncthing/config/config.xml`, and change the address `127.0.0.1` to `0.0.0.0` (line 100 approximately). Exit and save. I have this file because I already ran syncthing several times before this, and syncthing has already been initialized.
4. And then just start syncthing. The command is exactly the same as the option 'start syncthing'.
5. I changed back the ip address to secure my connection.

I guess there's some problem with the existing JSON file. I just checked my previous log: 'INFO: Access the GUI via the following URL: http://127.0.0.1:8080/'. I suspect that the gui-address argument may not be compatible with the latest syncthing binary anymore.

**Comment by gutenye** [comment]
Thanks for the solution, can you create a PR with step 3?

**Comment by zerone01y** [comment]
> 

This step is done manually. 
Btw, after this success, I can visit the GUI webpage by enabling it via KUAL without a problem. Just share in case anyone has the same issue.

**Comment by gutenye** [comment]
`Start Syncthing INSECURE Admin` has `-gui-address 'http://0.0.0.0:8080'` , this didn't work for you?

https://github.com/gutenye/syncthing-kindle/blob/2507b429fa936ce42e3bd47f7a9db8976756a024/syncthing/menu.json#L11

**Comment by TexKiller** [comment]
@gutenye What worked for me was having separated actions to open each firewall port (everything in the same action with semicolons did not open any of the ports). The other steps mentioned by @zerone01y shouldn't be required as long as he uses the INSECURE action, but I figure he had to open the port manually because the firewall action didn't work for him either.

**Comment by zerone01y** [comment]
Yes indeed. 

I later figured out that I need to open the port 8080 manually, and everything works fine after that.

> @gutenye What worked for me was having separated actions to open each firewall port (everything in the same action with semicolons did not open any of the ports). The other steps mentioned by @zerone01y shouldn't be required as long as he uses the INSECURE action, but I figure he had to open the port manually because the firewall action didn't work for him either.

**Comment by TexKiller** [comment]
After some more testing I believe the problem originated from the lack of spaces surrounding semicolons in the firewall action. I've created a small PR to fix that and to add some actions to close the ports if necessary. It might be a good idea to instruct users to close down the INSECURE Admin port after the initial configuration, to avoid leaving the 8080 port open.

**Comment by gutenye** [comment]
> It might be a good idea to instruct users to close down the INSECURE Admin port after the initial configuration, to avoid leaving the 8080 port open.

Can you also update the README?

**Comment by TexKiller** [comment]
Is this good? #7

**Comment by zenminimalist** [comment]
Yeah, nothing is working for me. I have tried the 4 passwords from the password generator site. It still keeps me asking for a password when trying to ssh into my Kindle PW Sig. Edition.

Any idea what other things to try?

**Comment by zerone01y** [comment]
> Yeah, nothing is working for me. I have tried the 4 passwords from the password generator site. It still keeps me asking for a password when trying to ssh into my Kindle PW Sig. Edition.
> 
> Any idea what other things to try?

I have no problem using syncthing with the current config, and there's no need to ssh into the kindle anymore.
